2013-08-19 07:24:31,809 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(88)]: --------------------------------------------------------------------------------
2013-08-19 07:24:31,811 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(89)]: JPPF version information: Version: 3.3.4, Build number: 1146, Build date: 2013-07-08 05:41 PDT
2013-08-19 07:24:31,811 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(90)]: starting client with PID=6396, UUID=F9C3DAD6-AE8D-89A0-1ECD-6C92FBE2C086
2013-08-19 07:24:31,812 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(91)]: --------------------------------------------------------------------------------
2013-08-19 07:24:31,812 [INFO ][org.jppf.client.AbstractGenericClient.<init>(102)]: JPPF client starting with sslEnabled = false
2013-08-19 07:24:32,896 [INFO ][org.jppf.client.AbstractGenericClient.newConnection(236)]: connection [driver-1] created
2013-08-19 07:24:32,928 [INFO ][org.jppf.client.ClassServerDelegateImpl.init(80)]: [client: driver-1 - ClassServer] Attempting connection to the class server at blackmachine:11111
2013-08-19 07:24:32,935 [INFO ][org.jppf.client.ClassServerDelegateImpl.init(91)]: [client: driver-1 - ClassServer] Reconnected to the class server
2013-08-19 08:00:24,224 [WARN ][org.jppf.client.ClassServerDelegateImpl.run(125)]: [driver-1 - ClassServer] caught java.net.SocketException: Connection reset, will re-initialise ...
2013-08-19 08:00:24,224 [INFO ][org.jppf.client.ClassServerDelegateImpl.init(80)]: [client: driver-1 - ClassServer] Attempting connection to the class server at blackmachine:11111
2013-08-19 08:00:24,228 [ERROR][org.jppf.client.BaseJPPFClientConnection.receiveBundleAndResults(242)]: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.jppf.comm.socket.AbstractSocketWrapper.readInt(AbstractSocketWrapper.java:264)
	at org.jppf.io.SocketWrapperInputSource.readInt(SocketWrapperInputSource.java:90)
	at org.jppf.io.IOHelper.readData(IOHelper.java:120)
	at org.jppf.io.IOHelper.unwrappedData(IOHelper.java:186)
	at org.jppf.client.BaseJPPFClientConnection.receiveBundleAndResults(BaseJPPFClientConnection.java:212)
	at org.jppf.client.BaseJPPFClientConnection.receiveResults(BaseJPPFClientConnection.java:260)
	at org.jppf.client.BaseJPPFClientConnection.receiveResults(BaseJPPFClientConnection.java:277)
	at org.jppf.client.balancer.ChannelWrapperRemote$RemoteRunnable.run(ChannelWrapperRemote.java:252)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
2013-08-19 08:00:24,229 [WARN ][org.jppf.client.balancer.ChannelWrapperRemote.run(267)]: java.net.SocketException: Connection reset
